name: Generate GitHub Profile Visuals

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  profile-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Hariom7201

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Hariom7201
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publish generated assets
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: dist
